apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
  annotations: 
    secret.k8s.aws/secret-arn: arn:aws:secretsmanager:us-west-2:123456789012:secret:catsndogs/unicorn-8VPgCY
spec:
  serviceAccountName: secretsmanagerrw
  volumes:
    - name: secret-vol
      emptyDir:
        medium: Memory
  containers:
  - name: myapp-container
    image: busybox:1.28
    command: ['sh', '-c', 'echo $(cat /tmp/secret) && sleep 3600']
    volumeMounts:
      - name: secret-vol
        mountPath: /tmp
  initContainers:
  - name: aws-secrets-manager
    image: amazon/aws-secrets-manager-secret-sidecar:v0.1.1
    env:
      - name: SECRET_ARN
        valueFrom:
          fieldRef: 
            fieldPath: metadata.annotations['secret.k8s.aws/secret-arn']
    volumeMounts:
      - name: secret-vol
        mountPath: /tmp
